apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiz-2048
  template:
    metadata:
      labels:
        app: wiz-2048
    spec:
      containers:
        - name: tasky
      image: 767828727505.dkr.ecr.us-east-1.amazonaws.com/tasky:latest
      ports:
        - containerPort: 8080
      env:
        - name: MONGO_URI
          value: "mongodb://admin:WizSecurePass123%21@192.168.6.81:27017/?authSource=admin"


---
apiVersion: v1
kind: Service
metadata:
  name: wiz-web
spec:
  type: LoadBalancer
  selector:
    app: wiz-2048
  ports:
    - port: 80
      targetPort: 80
