name: Terraform CI

on:
  push:
    paths:
      - 'Exercise/terraform/**'
    branches:
      - main
  pull_request:
    paths:
      - 'Exercise/terraform/**'

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: Exercise/terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: Exercise/terraform

      - name: Terraform Plan
        run: terraform plan -var="key_pair_name=wiz-keypair"
        working-directory: Exercise/terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var="key_pair_name=wiz-keypair"
        working-directory: Exercise/terraform
