name: Terraform CI

on:
  push:
    paths:
      - 'Exercise/terraform/**'
    branches:
      - main
  pull_request:
    paths:
      - 'Exercise/terraform/**'

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Exercise/terraform

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Show environment
        run: env | sort

      - name: Debug Secret Value
        run: echo "Using key pair: $TF_VAR_key_pair_name"
        env:
          TF_VAR_key_pair_name: ${{ secrets.EC2_KEY_PAIR_NAME }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="key_pair_name=${{ secrets.EC2_KEY_PAIR_NAME }}"


      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var="key_pair_name=${{ secrets.EC2_KEY_PAIR_NAME }}"

